alias ..='cd ..'
alias ...='cd ../../'
alias allinone='sudo apt update && sudo apt upgrade -y && sudo apt autoremove && sudo apt autoclean && sudo apt clean'
alias doc='/usr/local/bin/docker-compose '
alias docsp='docker system prune -f'
alias docvp='docker volume prune -f'

alias p3='python3'
alias i3='ipython3'
alias ins='sudo apt-get install'
alias px='ps aux | grep'
